### ISSUE TITLE
Bugs: hide-and-seek

### ISSUE THREAD

**Issue by fherrerao** [sergiogval/hide-and-seek#1]
#### In order to comply with the specification, I suggest that you fix the following issues in the formV.js file:

- [x] You may find the first issue in line 7 you are comparing lowercase, and in your code, you have to toUpperCase [link](https://github.com/sergiogval/hide-and-seek/blob/c745b00b5f06bd3d2d4d17a1a55ac227d2f8ca63/formV.js#L7)

- [x] You will find the second one in line 16. It's about the quotation to specify a string. Remember that you have to use the same quote type to open and close the string. [link](https://github.com/sergiogval/hide-and-seek/blob/c745b00b5f06bd3d2d4d17a1a55ac227d2f8ca63/formV.js#L16)

**Comment by sergiogval** [comment]
Thanks for your observations. I've applied to my code.
